[package]
name = "ornery-bot"
version = "0.1.0"
authors = ["SheepTester <ussa.say@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = { version = "0.8", features = ["client", "gateway", "rustls_backend", "model"] }
dotenv = "0.15.0"
tokio = { version = "0.2", features = ["macros"] }
async-trait = "0.1.41"
